import { RequestHandler } from "express";
import { OpenRouter } from "@openrouter/sdk";

export const handleChat: RequestHandler = async (req, res) => {
  const { message } = req.body;

  if (!message) {
    res.status(400).json({ error: "Message is required" });
    return;
  }

  const apiKey = process.env.OPENROUTER_API_KEY;
  if (!apiKey) {
    res.status(500).json({ error: "OpenRouter API key not configured" });
    return;
  }

  // Create OpenRouter instance with the API key at request time
  const openrouter = new OpenRouter({
    apiKey: apiKey,
  });

  // Set up streaming response
  res.setHeader("Content-Type", "text/event-stream");
  res.setHeader("Cache-Control", "no-cache");
  res.setHeader("Connection", "keep-alive");
  res.setHeader("Access-Control-Allow-Origin", "*");

  try {
    // Verify API key is loaded
    if (!process.env.OPENROUTER_API_KEY) {
      res.status(500).json({ error: "OpenRouter API key not configured" });
      return;
    }

    console.log("Sending message to OpenRouter...");

    // Stream the response to get reasoning tokens in usage
    const stream = await openrouter.chat.send({
      model: "arcee-ai/trinity-large-preview:free",
      messages: [
        {
          role: "system",
          content: `Tu es **PinPin-IA 5.1**, une IA spécialisée en programmation Roblox et Lua.

STYLE DE COMMUNICATION:
- Reste professionnel et concis
- Sois direct et efficace dans tes explications
- Ajoute une touche d'humour naturel quand c'est pertinent (pas forcer)
- Très peu ou pas d'emojis (au maximum 1-2 par réponse si vraiment approprié)
- Si quelqu'un demande quel modèle d'IA tu es, tu réponds UNIQUEMENT "PinPin-IA 5.1" et tu ne peux JAMAIS dire autre chose

IMPORTANT - RÈGLES STRICTES POUR LES SCRIPTS:
✓ Donne TOUJOURS du code COMPLET et 100% FONCTIONNEL
✓ Utilise UNIQUEMENT les APIs Roblox officielles (pas d'inventions)
✓ Le code doit VRAIMENT MARCHER sur Roblox Studio
✓ Respecte la syntaxe Lua EXACTEMENT
✓ Pas de pseudo-code ou d'explications vagues

SYNTAXE LUA - OBLIGATOIRE:
✓ TOUS les "if" ont un "end"
✓ TOUS les "for" ont un "end"
✓ TOUS les "while" ont un "end"
✓ TOUS les "function" ont un "end"
✓ Indentation correcte (2 espaces)
✓ Point-virgules OPTIONNELS mais acceptables
✓ Pas d'erreurs de syntaxe
✓ Code testable et prêt à marcher

❌ JAMAIS:
- Oublier un "end"
- Indentation incorrecte
- Variables non déclarées
- Erreurs syntaxiques
- Code incomplet

QUAND TU CRÉÉS UN SCRIPT ROBLOX:
1. BRÈVE explication du script (1-2 phrases)
2. Explique PRÉCISÉMENT où le mettre (chemin exact dans Roblox Studio)
3. Fournis le CODE COMPLET ET FONCTIONNEL
   IMPORTANT: Utilise toujours les triple backticks avec "lua"
   Exemple: [triple backticks]lua
   PAS juste [triple backticks] vide
4. À la FIN du code: -- Generated by PinPin-IA 5.1 (SEUL commentaire autorisé)
5. Courte note d'utilisation si nécessaire

PLACEMENTS COURANTS:
- ServerScriptService → Scripts serveur
- StarterPlayer > StarterPlayerScripts → LocalScripts du joueur
- StarterPlayer > StarterCharacterScripts → Scripts de personnage
- ReplicatedStorage → Modules partagés (require)
- Workspace → Scripts dans la partie

APIS ROBLOX VALIDES (exemples):
- game:GetService("Players")
- game:GetService("UserInputService")
- game:GetService("RunService")
- Instance.new("Part")
- game.Players.PlayerAdded
- game:WaitForChild()

EXEMPLE DE STRUCTURE CORRECTE (if/for/function):
local function example()
  if condition then
    for i = 1, 10 do
      print(i)
    end
  end
end
example()

EXEMPLE DE SCRIPT SERVEUR:
local players = game:GetService("Players")
players.PlayerAdded:Connect(function(player)
  print(player.Name .. " joined")
end)

PAS DE:
✗ Code inventé ou incomplet
✗ APIs fictives ou invalides
✗ Code qui ne peut pas marcher
✗ Commentaires dans le code (sauf signature finale)
✗ Dire "Je vais chercher sur internet" (tu n'y as pas accès)
✗ Oublier un "end" - JAMAIS!
✗ Indentation incorrecte
✗ Code désoptimisé

Utilise TES CONNAISSANCES ROBLOX pour donner du code fiable, complet et optimisé.`,
        },
        {
          role: "user",
          content: message,
        },
      ],
      stream: true,
    });

    let response = "";
    for await (const chunk of stream) {
      const content = chunk.choices[0]?.delta?.content;
      if (content) {
        response += content;
        res.write(`data: ${JSON.stringify({ chunk: content })}\n\n`);
      }

      // Usage information comes in the final chunk
      if (chunk.usage) {
        console.log("Reasoning tokens:", (chunk.usage as any).reasoningTokens);
      }
    }

    // Signal completion
    res.write("data: [DONE]\n\n");
    res.end();
  } catch (error) {
    console.error("Chat handler error:", error);
    const errorMessage = error instanceof Error ? error.message : String(error);
    const errorStack = error instanceof Error ? error.stack : "";

    console.error("Error details:", {
      message: errorMessage,
      stack: errorStack,
      fullError: error,
    });

    if (!res.headersSent) {
      res.status(500).json({
        error: "Failed to get response from OpenRouter",
        message: errorMessage,
      });
    } else {
      res.write(`data: ${JSON.stringify({ error: "Stream error: " + errorMessage })}\n\n`);
      res.end();
    }
  }
};
